name: wayland_layer_shell
description: "A flutter plugin to create desktop components for Wayland using the Layer Shell protocol"
version: 1.0.1
homepage: https://github.com/Mr-1311/wayland_layer_shell
repository: https://github.com/Mr-1311/wayland_layer_shell

platforms:
  linux:

topics:
  - window
  - linux
  - wayland
  - layer-shell

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WaylandLayerShellPlugin
